Feat: #193 Move popup to right side
CasperDash/casperdash-client pull request #199
Opened 2022-12-28 17:48 UTC by hoailinh1210

### Summary (Please recap what you changed or fixed)
- Move the popup to the right side

![image](https://user-images.githubusercontent.com/20489407/209852247-5d1ea7a3-d65a-404a-b24f-22071f9f7d27.png)

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [x] My code has covered these test cases (please list down your tested cases):

2022-12-29 14:50 UTC, djhahe commented
@hoailinh1210  2 buttons is quite big, pls help to reduce the button size, single row is enough

2022-12-29 15:01 UTC, djhahe commented
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6711653/209971330-e137e856-9a23-4470-a574-c3ab59394ee5.png">

@hoailinh1210 pls check style on sign message popup

2022-12-29 15:28 UTC, djhahe commented
<img width="360" alt="image" src="https://user-images.githubusercontent.com/6711653/209973031-5bcaa290-5c28-41a6-85b7-43a409cc7cf9.png">
Pls follow settings page styles, content should be on white background, also we need a confirm popup on removing site

2022-12-29 15:30 UTC, djhahe requested changes

2022-12-29 15:30 UTC, djhahe commented on client/src/services/ServiceWorker/Controllers/PopupController.js
> +const NOTIFICATION_HEIGHT = 720;
pls use `width: 357px; height: 600px;` same with extension popup

2023-01-02 02:25 UTC, hoailinh1210 commented
Hi @djhahe, I updated 2 your comments, please take a look
> 



> <img alt="image" width="372" src="https://user-images.githubusercontent.com/6711653/209971330-e137e856-9a23-4470-a574-c3ab59394ee5.png">
> 
> @hoailinh1210 pls check style on sign message popup. I think we have enough space to show full message and pk

<img width="345" alt="image" src="https://user-images.githubusercontent.com/20489407/210191229-86a41bd2-eb62-4d2f-9c01-a1ca7665a90d.png">



> <img alt="image" width="360" src="https://user-images.githubusercontent.com/6711653/209973031-5bcaa290-5c28-41a6-85b7-43a409cc7cf9.png">
> 
> Pls follow settings page styles, content should be on white background, also we need a confirm popup on removing site

<img width="356" alt="image" src="https://user-images.githubusercontent.com/20489407/210191266-b561f0d3-e1ae-4307-b39a-b054e0207ede.png">

2023-01-02 03:17 UTC, djhahe commented
![image](https://user-images.githubusercontent.com/6711653/210192901-818c70a3-2e88-47db-8707-516814eba1a2.png)
@hoailinh1210 please help to update styles. There are h and v scrolls.

2023-01-03 03:22 UTC, djhahe approved these changes

2023-01-03 03:22 UTC, merged